[package]
name = "pankosmia_web"
description = "A web server for pankosmia desktop applications"
version = "0.1.5"
edition = "2021"
license = "MIT"
homepage = "https://xenizo.fr"
repository = "https://github.com/pankosmia/pankosmia-web"
readme = "README.md"

exclude = [
    "webfonts/*"
]

[lib]
name = "pankosmia_web"
crate-type = [
    "lib"
]
path = "src/lib.rs"

[dependencies]
fs = "0.0.5"
git2 = "0.19.0"
hallomai = "0.1.5"
home = "0.5.9"
rocket = "0.5.0"
rocket-multipart-form-data = "0.10.7"
s2n-quic = "1.48.0"
serde = "1.0.210"
serde_json = "1.0.132"
copy_dir = "0.1.3"
ureq = { version = "2.11.0", features = ["json"] }
tokio = "1.43.0"
